#we'll store here the models generated by the user in the app running the manage.py command

#sync_models() will be called by the manage.py command

# Path: generate_models.py

from db import connect_mongo, create_db
connect_mongo()

#sync_models() function:
# 1. get all the models from the database
# 2. create a new database
# 3. create a new collection for each model
# 4. create a new document for each model

def sync_models():
    #get all the models from the database
    models = get_models()
    #create a new database
    db = create_db('test')
    #create a new collection for each model
    for model in models:
        collection = db[model]
        #create a new document for each model
        collection.insert_one({'name': model})
        
def get_models():
    #get all the models from the database
    client = connect_mongo()
    db = client['test']
    models = db.list_collection_names()
    return models



    